### ISSUE TITLE
C++ Game Dev Youtube Channel

### ISSUE THREAD

**Issue by abouroubi** [krishnadevz/OpensourceResources#5]
One of the best Youtube channels to learn video game dev and C++.
https://www.youtube.com/channel/UC-yuWVUplUJZvieEligKBkA

@OneLoneCoder

**Comment by krishnadevz** [comment]
> 
> 
> One of the best Youtube channels to learn video game dev and C++.
> https://www.youtube.com/channel/UC-yuWVUplUJZvieEligKBkA

i will add or else you can send PR

**Comment by krishnadevz** [comment]
done added

**Comment by abouroubi** [comment]
@krishnadevz thanks
